# **Linear Regression (Multiple Regression)**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df = pd.read_csv('/content/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
# Data preprocessing
import math
# Taking median to fill the missing values
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [ ]:
# filling the missing value in the dataset
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
# creating linear regression class object
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [ ]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [ ]:
# coefficent*x1 + coefficent*bedrooms + coefficient*age + intercept
112.06244194*3000 + 23388.88007794*3 +(-3231.71790863)*40 + 221323.00186540396

498408.251574024

In [ ]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

# ** Hiring Excercise **

In [108]:
pip install word2number

In [109]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [110]:
df = pd.read_csv('/content/tableConvert.com_s9yhrm.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2        five                    6.0                           7      60000
3         two                   10.0                          10      65000
4       seven                    9.0                           6      70000
5       three                    7.0                          10      62000
6         ten                    NaN                           7      72000
7      eleven                    7.0                           8      80000

In [111]:
# Renaming column name
new_column = ['experience', 'test_score', 'interview_score', 'salary']
df.columns = new_column
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [112]:
df.experience = df.experience.fillna("zero")
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [113]:
df.experience = df.experience.apply(w2n.word_to_num)

In [96]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [114]:
meadian_test_score = math.floor(df['test_score'].mean())
meadian_test_score

7

In [115]:
df['test_score'] = df['test_score'].fillna(meadian_test_score)
print(df)

   experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000


In [116]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score', 'interview_score']], df.salary);

In [117]:
reg.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])